services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm install
    startCommand: npm start
    git:
      branch: main  # Ensure the branch name is 'main' if you're using it instead of 'master'
